### ISSUE TITLE
Million function helpers

### ISSUE THREAD

**Issue by aidenybai** [rajihawa/billion#3]
Heya - I've been experimenting around with some library like this - If you want to add JSX support you can check out some of the stuff we have here: https://github.com/millionjs/myna/tree/master/src

`createVNode.ts` and `jsx.ts` might be particularly helpful for your use case

**Comment by rajihawa** [comment]
Hey, Thanks so much for for suggesting this repo, it looks very promising, but I actually wanted to make the template engine something object based inspired by flutter, to get the maximum from typescript and autocomplete support, I still don't have a final idea on how the final template engine will look, but I'll defiantly check [myna](https://github.com/millionjs/myna/tree/master/src) out and see the best practices to intergrade templates with [million](https://github.com/millionjs/million).
and of course thanks for looking into my package, if it wasn't for [million](https://github.com/millionjs/million) this wouldn't be possible :D.

**Comment by aidenybai** [comment]
Sounds like a really cool idea! Always happy to help!
